version: "3.8"
services:
    fronted:
        build: ./frontend
        ports:
            - 3000:3000
    backend:
        build: ./backend
        ports:
            - 3001:3001
        environment:
            DB_URL: mongodb://database/coffee
    database:
        image: mongo:4.0-xenial
        ports:
            - 27017:27017
        volumes:
            - coffee:/data/db
volumes:
    coffee: